In [6]:
import requests
import pandas as pd
import re

In [7]:
anni = ["2013", "2014", "2015"]
mesi = ["01", "02", "03", "04", "05", "06","07", "08", "09", "10", "11", "12"]

In [10]:
# 2012 bisestile
newDF = pd.DataFrame(columns=["Ora","Grado","Giorno","Mese","Anno"])

def split_ora(ora):
    return re.findall('\d?\d\.\d\d', ora)

def split_gradi(gradi):
    return re.findall('[\-]?\d', gradi)


#2012
for j in mesi:
    if j == "01":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "02":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29"]
    elif j == "03":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "04":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30"]
    elif j == "05":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "06":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30"]
    elif j == "07":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "08":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "09":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30"]
    elif j == "10":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    elif j == "11":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30"]
    elif j == "12":
        giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
          "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
          "27", "28", "29", "30", "31"]
    for k in giorni:
        url = "https://www.timeanddate.com/scripts/cityajax.php?n=poland/warsaw&mode=historic&hd=2012" + j + k + "&month=" + j + "&year=2012&json=1"
        pagina_web = requests.get(url)
        pagina_web = pagina_web.text.split("{")
        g = 0
        maxloop = len(pagina_web)
        while g < maxloop-1:
            ora = pagina_web[g+2]
            gradi = pagina_web[g+4]
            newDF = newDF.append({'Ora': ora, 'Grado' : gradi, 'Giorno' : k, 'Mese' : j, 'Anno' : "2012"}, ignore_index=True)
            g += 10
            
newDF['GradoFix'] = newDF['Grado'].apply(split_gradi)

newDF['OraFix'] = newDF['Ora'].apply(split_ora)

newDF['OraFix2'] = ""

i = 0
while i < len(newDF.index):
    newDF.OraFix2[i] = ''.join(newDF.OraFix[i])
    newDF.GradoFix[i] = ''.join(newDF.GradoFix[i])
    i+=1

In [19]:
newDF.Ora[1]

'h:"00:30"},'

In [23]:
def split_ora(ora):
    return re.findall('\d+\:\d+', ora)

newDF['OraFix2'] = newDF['Ora'].apply(split_ora)
newDF

,Ora,Grado,Giorno,Mese,Anno,GradoFix,OraFix,OraFix2
0,"h:""00:00<br><span class=\""smaller soft\"">So, 1...","h:""0&nbsp;°C""},",01,01,2012,0,[],[00:00]
1,"h:""00:30""},","h:""-1&nbsp;°C""},",01,01,2012,-1,[],[00:30]
2,"h:""01:00""},","h:""-1&nbsp;°C""},",01,01,2012,-1,[],[01:00]
3,"h:""02:00""},","h:""-2&nbsp;°C""},",01,01,2012,-2,[],[02:00]
4,"h:""02:30""},","h:""-2&nbsp;°C""},",01,01,2012,-2,[],[02:30]
...,...,...,...,...,...,...,...,...
16908,"h:""21:30""},","h:""3&nbsp;°C""},",31,12,2012,3,[],[21:30]
16909,"h:""22:00""},","h:""2&nbsp;°C""},",31,12,2012,2,[],[22:00]
16910,"h:""22:30""},","h:""2&nbsp;°C""},",31,12,2012,2,[],[22:30]
16911,"h:""23:00""},","h:""2&nbsp;°C""},",31,12,2012,2,[],[23:00]
16912,"h:""23:30""},","h:""2&nbsp;°C""},",31,12,2012,2,[],[23:30]

In [24]:
i = 0
while i < len(newDF.index):
    newDF.OraFix2[i] = ''.join(newDF.OraFix2[i])
    #newDF.GradoFix[i] = ''.join(newDF.GradoFix[i])
    i+=1

patternDel = "\:[3]"
filterx = newDF.OraFix2.str.contains(patternDel)

newDF = newDF[~filterx]

newDF

,Ora,Grado,Giorno,Mese,Anno,GradoFix,OraFix,OraFix2
0,"h:""00:00<br><span class=\""smaller soft\"">So, 1...","h:""0&nbsp;°C""},",01,01,2012,0,[],00:00
2,"h:""01:00""},","h:""-1&nbsp;°C""},",01,01,2012,-1,[],01:00
3,"h:""02:00""},","h:""-2&nbsp;°C""},",01,01,2012,-2,[],02:00
5,"h:""03:00""},","h:""-2&nbsp;°C""},",01,01,2012,-2,[],03:00
7,"h:""04:00""},","h:""-1&nbsp;°C""},",01,01,2012,-1,[],04:00
...,...,...,...,...,...,...,...,...
16903,"h:""19:00""},","h:""5&nbsp;°C""},",31,12,2012,5,[],19:00
16905,"h:""20:00""},","h:""4&nbsp;°C""},",31,12,2012,4,[],20:00
16907,"h:""21:00""},","h:""4&nbsp;°C""},",31,12,2012,4,[],21:00
16909,"h:""22:00""},","h:""2&nbsp;°C""},",31,12,2012,2,[],22:00
16911,"h:""23:00""},","h:""2&nbsp;°C""},",31,12,2012,2,[],23:00

In [25]:
newDF.drop(['Ora', 'Grado', 'OraFix'], axis=1, inplace=True)

/Users/alessandropontini/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [27]:
# salvo temperature
newDF.to_csv("/Users/alessandropontini/Desktop/temperature_2012.csv", index=False)

In [36]:
newDF2 = pd.DataFrame(columns=["Ora","Grado","Giorno","Mese","Anno"])

In [44]:
# 2013 2014 2015

for i in anni:
    for j in mesi:
        if j == "01":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "02":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28"]
        elif j == "03":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "04":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30"]
        elif j == "05":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "06":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30"]
        elif j == "07":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "08":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "09":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30"]
        elif j == "10":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]
        elif j == "11":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30"]
        elif j == "12":
            giorni = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
              "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
              "27", "28", "29", "30", "31"]

        for k in giorni:
            url = "https://www.timeanddate.com/scripts/cityajax.php?n=poland/warsaw&mode=historic&hd="+ i + j + k + "&month=" + j + "&year=" + i + "&json=1"
            pagina_web = requests.get(url)
            pagina_web = pagina_web.text.split("{")
            g = 0
            maxloop = len(pagina_web)
            while g < maxloop-1:
                ora = pagina_web[g+2]
                gradi = pagina_web[g+4]
                newDF2 = newDF2.append({'Ora': ora, 'Grado' : gradi, 'Giorno' : k, 'Mese' : j, 'Anno' : i}, ignore_index=True)
                g += 10
                    
newDF2['GradoFix'] = newDF2['Grado'].apply(split_gradi)
newDF2['OraFix'] = newDF2['Ora'].apply(split_ora)

In [49]:
i = 0
while i < len(newDF2.index):
    newDF2.OraFix[i] = ''.join(newDF2.OraFix[i])
    newDF2.GradoFix[i] = ''.join(newDF2.GradoFix[i])
    i+=1

,Ora,Grado,Giorno,Mese,Anno,GradoFix,OraFix
0,"h:""00:00<br><span class=\""smaller soft\"">di 1 ...","h:""1&nbsp;°C""},",01,01,2013,1,00:00
1,"h:""00:30""},","h:""1&nbsp;°C""},",01,01,2013,1,00:30
2,"h:""01:00""},","h:""1&nbsp;°C""},",01,01,2013,1,01:00
3,"h:""01:30""},","h:""2&nbsp;°C""},",01,01,2013,2,01:30
4,"h:""02:00""},","h:""2&nbsp;°C""},",01,01,2013,2,02:00
...,...,...,...,...,...,...,...
77692,"h:""21:30""},","h:""-7&nbsp;°C""},",31,12,2015,-7,21:30
77693,"h:""22:00""},","h:""-7&nbsp;°C""},",31,12,2015,-7,22:00
77694,"h:""22:30""},","h:""-8&nbsp;°C""},",31,12,2015,-8,22:30
77695,"h:""23:00""},","h:""-8&nbsp;°C""},",31,12,2015,-8,23:00
77696,"h:""23:30""},","h:""-8&nbsp;°C""},",31,12,2015,-8,23:30

In [50]:
patternDel = "\:[3]"
filterx = newDF2.OraFix.str.contains(patternDel)

newDF2 = newDF2[~filterx]

newDF2

,Ora,Grado,Giorno,Mese,Anno,GradoFix,OraFix
0,"h:""00:00<br><span class=\""smaller soft\"">di 1 ...","h:""1&nbsp;°C""},",01,01,2013,1,00:00
2,"h:""01:00""},","h:""1&nbsp;°C""},",01,01,2013,1,01:00
4,"h:""02:00""},","h:""2&nbsp;°C""},",01,01,2013,2,02:00
6,"h:""03:00""},","h:""2&nbsp;°C""},",01,01,2013,2,03:00
8,"h:""04:00""},","h:""1&nbsp;°C""},",01,01,2013,1,04:00
...,...,...,...,...,...,...,...
77687,"h:""19:00""},","h:""-5&nbsp;°C""},",31,12,2015,-5,19:00
77689,"h:""20:00""},","h:""-7&nbsp;°C""},",31,12,2015,-7,20:00
77691,"h:""21:00""},","h:""-7&nbsp;°C""},",31,12,2015,-7,21:00
77693,"h:""22:00""},","h:""-7&nbsp;°C""},",31,12,2015,-7,22:00
77695,"h:""23:00""},","h:""-8&nbsp;°C""},",31,12,2015,-8,23:00

In [52]:
newDF2.drop(['Ora', 'Grado'], axis=1, inplace=True)

/Users/alessandropontini/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [54]:
newDF2.to_csv("/Users/alessandropontini/Desktop/temperature3anni.csv", index=False)

In [56]:
newDF.rename(columns={'OraFix2':'OraFix'}, inplace=True)
frames = [newDF, newDF2]
totale = pd.concat(frames, ignore_index=True)
totale

/Users/alessandropontini/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

      Giorno Mese  Anno GradoFix OraFix
0         01   01  2012        0  00:00
1         01   01  2012       -1  01:00
2         01   01  2012       -2  02:00
3         01   01  2012       -2  03:00
4         01   01  2012       -1  04:00
...      ...  ...   ...      ...    ...
47565     31   12  2015       -5  19:00
47566     31   12  2015       -7  20:00
47567     31   12  2015       -7  21:00
47568     31   12  2015       -7  22:00
47569     31   12  2015       -8  23:00

[47570 rows x 5 columns]

In [57]:
totale.to_csv("/Users/alessandropontini/Desktop/tot_temperature.csv", index=False)