In [4]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 

# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data1 = pd.read_csv("C:/Users/vizzi/Documents/temperature_toto_2012.csv") 

# Preview the first 5 lines of the loaded data 
data1.head()

   Giorno  Mese  Anno  GradoFix OraFix2
0       1     1  2012      -9.0   00:20
1       1     1  2012      -9.0   00:50
2       1     1  2012      -9.0   01:50
3       1     1  2012      -9.0   02:20
4       1     1  2012      -9.0   02:50

In [3]:
i = 0
while i < len(data1.index):
    data1.OraFix2[i] = ''.join(data1.OraFix2[i])
    #newDF.GradoFix[i] = ''.join(newDF.GradoFix[i])
    i+=1

patternDel = "\:[2]"
filterx = data1.OraFix2.str.contains(patternDel)

data11 = data1[~filterx]

data11

C:\Users\vizzi\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

       Giorno  Mese  Anno  GradoFix OraFix2
1           1     1  2012      -9.0   00:50
2           1     1  2012      -9.0   01:50
4           1     1  2012      -9.0   02:50
6           1     1  2012      -9.0   03:50
8           1     1  2012      -8.0   04:50
10          1     1  2012      -7.0   05:50
12          1     1  2012      -6.0   06:50
14          1     1  2012      -4.0   07:50
15          1     1  2012      -3.0   08:50
17          1     1  2012      -2.0   09:50
19          1     1  2012       0.0   10:50
21          1     1  2012       1.0   11:50
23          1     1  2012       1.0   12:50
25          1     1  2012       1.0   13:50
27          1     1  2012       2.0   14:50
29          1     1  2012       2.0   15:50
31          1     1  2012       1.0   16:50
33          1     1  2012       2.0   17:50
35          1     1  2012       2.0   18:50
37          1     1  2012       2.0   19:50
39          1     1  2012       3.0   20:50
41          1     1  2012       3.0   21:50
43          1     1  2012       3.0   22:50
45          1     1  2012       3.0   23:50
47          2     1  2012       3.0   00:50
49          2     1  2012       3.0   01:50
51          2     1  2012       4.0   02:50
53          2     1  2012       4.0   03:50
55          2     1  2012       4.0   04:50
57          2     1  2012       4.0   05:50
...       ...   ...   ...       ...     ...
16752      30    12  2012       4.0   18:50
16754      30    12  2012       4.0   19:50
16756      30    12  2012       4.0   20:50
16758      30    12  2012       3.0   21:50
16760      30    12  2012       3.0   22:50
16762      30    12  2012       2.0   23:50
16764      31    12  2012       2.0   00:50
16766      31    12  2012       2.0   01:50
16768      31    12  2012       2.0   02:50
16770      31    12  2012       2.0   03:50
16772      31    12  2012       2.0   04:50
16774      31    12  2012       2.0   05:50
16776      31    12  2012       2.0   06:50
16778      31    12  2012       2.0   07:50
16780      31    12  2012       3.0   08:50
16782      31    12  2012       3.0   09:50
16784      31    12  2012       3.0   10:50
16786      31    12  2012       3.0   11:50
16788      31    12  2012       3.0   12:50
16790      31    12  2012       3.0   13:50
16792      31    12  2012       3.0   14:50
16794      31    12  2012       3.0   15:50
16796      31    12  2012       3.0   16:50
16798      31    12  2012       3.0   17:50
16800      31    12  2012       4.0   18:50
16802      31    12  2012       4.0   19:50
16804      31    12  2012       5.0   20:50
16806      31    12  2012       5.0   21:50
16808      31    12  2012       5.0   22:50
16810      31    12  2012       6.0   23:50

[8546 rows x 5 columns]

In [6]:
# salvo temperature
data11.to_csv("C:/Users/vizzi/Documents/temperature_toto_2012_pulito.csv", index=False)

In [4]:
data2 = pd.read_csv("C:/Users/vizzi/Documents/temperature_toto_2013.csv") 

data2.head()

   Giorno  Mese  Anno GradoFix OraFix2
0       1     1  2013    ['5']   12:20
1       1     1  2013    ['5']   12:50
2       1     1  2013    ['5']    1:20
3       1     1  2013    ['5']    1:50
4       1     1  2013    ['5']    2:20

In [11]:
i = 0
while i < len(data2.index):
    data2.OraFix2[i] = ''.join(data2.OraFix2[i])
    data2.GradoFix[i] = ''.join(data2.GradoFix[i])
    i+=1

C:\Users\vizzi\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\vizzi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

KeyboardInterrupt:

In [8]:
data2.head()

   Giorno  Mese  Anno GradoFix OraFix2
0       1     1  2013    ['5']   12:20
1       1     1  2013    ['5']   12:50
2       1     1  2013    ['5']    1:20
3       1     1  2013    ['5']    1:50
4       1     1  2013    ['5']    2:20

In [ ]:
patternDel = "\:[2]"
filterx = data2.OraFix2.str.contains(patternDel)

data22 = data2[~filterx]

data22

In [ ]:
data22.reset_index(inplace=True, drop=True)

In [ ]:
#i = 0
#while i < len(data22.index):
   # data22.GradoFix[i] = ''.join(data22.GradoFix[i])
   # i+=1

In [28]:
data22

      Giorno  Mese  Anno GradoFix OraFix2
0          1     1  2013    ['5']   12:50
1          1     1  2013    ['5']    1:50
2          1     1  2013    ['5']    2:50
3          1     1  2013    ['5']    3:50
4          1     1  2013    ['5']    4:50
5          1     1  2013    ['5']    5:50
6          1     1  2013    ['5']    6:50
7          1     1  2013    ['5']    7:50
8          1     1  2013    ['5']    8:50
9          1     1  2013    ['5']    9:50
10         1     1  2013    ['5']   10:50
11         1     1  2013    ['5']   11:50
12         1     1  2013    ['5']   12:50
13         1     1  2013    ['5']    1:52
14         1     1  2013    ['4']    2:50
15         1     1  2013    ['4']    3:50
16         1     1  2013    ['3']    4:50
17         1     1  2013    ['3']    5:50
18         1     1  2013    ['3']    6:50
19         1     1  2013    ['3']    7:50
20         1     1  2013    ['3']    8:50
21         1     1  2013    ['3']    9:50
22         1     1  2013    ['2']   10:50
23         1     1  2013    ['2']   11:50
24         2     1  2013    ['2']   12:50
25         2     1  2013    ['2']    1:50
26         2     1  2013    ['2']    2:50
27         2     1  2013    ['3']    3:50
28         2     1  2013    ['3']    4:50
29         2     1  2013    ['3']    5:50
...      ...   ...   ...      ...     ...
8483      30    12  2013    ['3']    2:50
8484      30    12  2013    ['2']    3:50
8485      30    12  2013    ['1']    4:50
8486      30    12  2013    ['3']    5:50
8487      30    12  2013    ['4']    6:50
8488      30    12  2013    ['3']    7:50
8489      30    12  2013    ['3']    9:50
8490      30    12  2013    ['3']   10:50
8491      30    12  2013    ['3']   11:50
8492      31    12  2013    ['2']   12:50
8493      31    12  2013    ['2']    1:50
8494      31    12  2013    ['2']    2:50
8495      31    12  2013    ['3']    4:50
8496      31    12  2013    ['4']    6:50
8497      31    12  2013    ['4']    7:50
8498      31    12  2013    ['3']    8:50
8499      31    12  2013    ['3']    9:50
8500      31    12  2013    ['3']   10:50
8501      31    12  2013    ['4']   12:50
8502      31    12  2013    ['4']    1:50
8503      31    12  2013    ['4']    2:50
8504      31    12  2013    ['4']    3:50
8505      31    12  2013    ['5']    4:50
8506      31    12  2013    ['5']    5:50
8507      31    12  2013    ['4']    6:50
8508      31    12  2013    ['4']    7:50
8509      31    12  2013    ['4']    8:50
8510      31    12  2013    ['4']    9:50
8511      31    12  2013    ['4']   10:50
8512      31    12  2013    ['3']   11:50

[8513 rows x 5 columns]

In [17]:
# salvo temperature
data22.to_csv("C:/Users/vizzi/Documents/temperature_toto_2013_pulito.csv", index=False)

In [ ]:
data3 = pd.read_csv("C:/Users/vizzi/Documents/temperature_toto_2014.csv") 

# Preview the first 5 lines of the loaded data 
data3.head()

In [ ]:
i = 0
while i < len(data3.index):
    data3.OraFix2[i] = ''.join(data3.OraFix2[i])
    data3.GradoFix[i] = ''.join(data3.GradoFix[i])
    i+=1
patternDel = "\:[2]"
filterx = data3.OraFix2.str.contains(patternDel)

data33 = data3[~filterx]

data33.reset_index(inplace=True, drop=True)
data33

In [1]:
#################################################################
###########################################
#####################

In [6]:
data2 = pd.read_csv("C:/Users/vizzi/Documents/orginale/temperature_toto_2013secondo_ok.csv") 

# Preview the first 5 lines of the loaded data 
data2.head()

,Ora,Grado,Giorno,Mese,Anno,GradoFix,OraFix
0,"h:""00:20<br><span class=\""smaller soft\"">Di, 1...","h:""5&nbsp;°C""},",1,1,2013,['5'],[]
1,"h:""00:50""},","h:""5&nbsp;°C""},",1,1,2013,['5'],[]
2,"h:""01:20""},","h:""5&nbsp;°C""},",1,1,2013,['5'],[]
3,"h:""01:50""},","h:""5&nbsp;°C""},",1,1,2013,['5'],[]
4,"h:""02:20""},","h:""5&nbsp;°C""},",1,1,2013,['5'],[]

In [ ]:
i = 0
while i < len(data2.index):
    data2.OraFix[i] = ''.join(data2.OraFix[i])
    data2.GradoFix[i] = ''.join(data2.GradoFix[i])
    i+=1

In [ ]:
patternDel = "\.[20]"
filterx = newDF2.OraFix.str.contains(patternDel)

newDF2 = newDF2[~filterx]

newDF2.head()